module "aws_vpc" {
  source = "../modules/aws-vpc"
  vpc_name = var.vpc_name
  vpc_cidr_block = var.vpc_cidr_block
  igw_name = var.igw_name
  public_subnet_1_cidr_block = var.public_subnet_1_cidr_block
  public_subnet_2_cidr_block = var.public_subnet_2_cidr_block
  public_subnet_3_cidr_block = var.public_subnet_3_cidr_block
  private_subnet_1_cidr_block = var.private_subnet_1_cidr_block
  private_subnet_2_cidr_block = var.private_subnet_2_cidr_block
  private_subnet_3_cidr_block = var.private_subnet_3_cidr_block
  public_subnet_1_name = var.public_subnet_1_name
  public_subnet_2_name = var.public_subnet_2_name
  public_subnet_3_name = var.public_subnet_3_name
  private_subnet_1_name = var.private_subnet_1_name
  private_subnet_2_name = var.private_subnet_2_name
  private_subnet_3_name = var.private_subnet_3_name
  public_subnet_1_az = var.public_subnet_1_az
  public_subnet_2_az = var.public_subnet_2_az
  public_subnet_3_az = var.public_subnet_3_az
  private_subnet_1_az = var.private_subnet_1_az
  private_subnet_2_az = var.private_subnet_2_az
  private_subnet_3_az = var.private_subnet_3_az
  public_rt_name = var.public_rt_name
  private_1_rt_name = var.private_1_rt_name
  private_2_rt_name = var.private_2_rt_name
  private_3_rt_name = var.private_3_rt_name
}
